# Generated by Django 3.1.2 on 2020-10-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0007_auto_20201020_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='films',
        ),
        migrations.AddField(
            model_name='film',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='films', to='api_project.People'),
        ),
    ]
