# Generated by Django 3.1.2 on 2020-10-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0008_auto_20201020_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='characters',
        ),
        migrations.AddField(
            model_name='people',
            name='films',
            field=models.ManyToManyField(blank=True, related_name='characters', to='api_project.Film'),
        ),
    ]
