# Generated by Django 3.1.2 on 2020-10-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0009_auto_20201020_0349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
