# Generated by Django 3.1.2 on 2020-10-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0011_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='films',
            field=models.ManyToManyField(blank=True, related_name='films', to='api_project.Film'),
        ),
    ]
