# Generated by Django 3.1.2 on 2020-10-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0012_people_films'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='films',
            field=models.ManyToManyField(related_name='films', to='api_project.Film'),
        ),
    ]
