# Generated by Django 3.1.2 on 2020-10-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0013_auto_20201025_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='films',
            field=models.ManyToManyField(blank=True, related_name='characters', to='api_project.Film'),
        ),
    ]
