# Generated by Django 3.1.2 on 2020-10-28 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0015_auto_20201025_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='people',
            name='hair_color',
        ),
        migrations.RemoveField(
            model_name='people',
            name='mass',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='orbital_period',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='rotation_period',
        ),
    ]
